### ISSUE TITLE
make oPermutive an npm package

### ISSUE THREAD

**Issue by andrewgeorgiou1981** [Financial-Times/o-permutive#8]
Out of the box Origami components are can be deployed via the Origami Build Service or can be consumed via Bower.
We should make this component NPM compatible as this will make it easier for developers to include the package into their build-pipelines.

**Comment by notlee** [comment]
👋 Origami components are also published to npm, `obt init` provides the tools out of the box.
ClircleCI Publish step: https://github.com/Financial-Times/o-permutive/blob/master/.circleci/config.yml#L18
o-permutive on npm: https://www.npmjs.com/package/@financial-times/o-permutive

**Comment by andrewgeorgiou1981** [comment]
Thanks @notlee and @alexflorisca, my mistake, i will close this issue.

Cheers
